language: python

cache:
  directories:
    - $HOME/.pip-cache/

env:
 - "PIP_DOWNLOAD_CACHE=$HOME/.pip-cache/"

services:
  - mongodb

notifications:
  email: false
  
python:
  - "2.7"
  
before_install: # Installing scipy deps: http://stackoverflow.com/a/14541175
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran libopenblas-dev liblapack-dev

install:
  - pip install -q --exists-action w -r requirements/edx/paver.txt
  - pip install -q --exists-action w python-memcached

script:
  - paver test
